import { tv } from '@/libs/twVariants.lib'

export const tabsStyle = tv({
  slots: {
    container: 'relative rounded-tabs-container-border-radius-default border border-solid border-b-tabs-container-border-bottom-color-default border-l-tabs-container-border-left-color-default border-r-tabs-container-border-right-color-default border-t-tabs-container-border-top-color-default bg-tabs-container-bg-color-default px-tabs-container-padding-x-default py-tabs-container-padding-y-default',
    indicator: 'absolute bottom-0 left-0 h-tabs-indicator-height-default w-[--reka-tabs-indicator-size] translate-x-[--reka-tabs-indicator-position] rounded-tabs-indicator-border-radius-default border border-solid border-b-tabs-indicator-border-bottom-color-default border-l-tabs-indicator-border-left-color-default border-r-tabs-indicator-border-right-color-default border-t-tabs-indicator-border-top-color-default bg-tabs-indicator-bg-color-default shadow-tabs-indicator-shadow-default duration-200',
    item: 'group px-tabs-item-container-padding-x-default py-tabs-item-container-padding-y-default outline-none',
    itemContent: 'relative z-tabs-item flex items-center rounded-tabs-item-border-radius-default bg-tabs-item-bg-color-default px-tabs-item-padding-x-default py-tabs-item-padding-y-default text-tabs-item-font-size-default font-tabs-item-font-weight-default text-tabs-item-text-color-default ring-tabs-item-ring-color-default ring-offset-1 duration-200 group-hover:bg-tabs-item-bg-color-hover group-hover:text-tabs-item-text-color-hover group-focus-visible:!bg-tabs-item-bg-color-focus group-focus-visible:!text-tabs-item-text-color-focus group-focus-visible:ring-2 group-data-[disabled]:cursor-not-allowed group-data-[disabled]:bg-tabs-item-bg-color-disabled group-data-[state=active]:bg-tabs-item-bg-color-active group-data-[disabled]:text-tabs-item-text-color-disabled group-data-[state=active]:text-tabs-item-text-color-active group-hover:group-data-[state=active]:bg-tabs-item-bg-color-active group-hover:group-data-[state=active]:text-tabs-item-text-color-active',
  },
})
