packages:
  - docs
  - "packages/*"

catalog:
  "vue": "3.5.13"
  "motion-v": "1.0.0-beta.0"
  "vue-i18n": "11.1.2"
  "@fontsource-variable/inter": "5.2.5"
  "@vueuse/core": "13.0.0"
  "@vueuse/router": "13.0.0"
  "@wisemen/eslint-config-vue": "1.2.0-beta.1"
  "eslint": "9.23.0"
  "husky": "^9.1.7"
  "reka-ui": "2.2.0"
  "tailwindcss": "4.1.2"
  "typescript": "5.8.2"
  "vite": "6.2.5"
  "vite-plugin-dts": "4.5.3"
  "vitest": "3.1.1"
  "vue-router": "4.5.0"
  "vue-tsc": "2.2.8"
  "tailwind-variants": "1.0.0"
  "tailwind-merge": "3.1.0"
  "@vitejs/plugin-vue": "5.2.3"
  "@tailwindcss/vite": "4.1.2"
  "@types/node": "22.14.0"
  "@vue/test-utils": "2.4.6"
  "@vue/tsconfig": "0.7.0"
  "turbo": "2.5.0"
  "rimraf": "6.0.1"
  "@tanstack/vue-query": "5.71.5"
  "unbuild": "3.5.0"
  "jsdom": "26.0.0"
  "bumpp": "10.1.0"
  "ts-node": "10.9.2"
  "esno": "4.8.0"
  "zod": "3.24.2"
