packages:
  - docs
  - "packages/*"

catalog:
  "vue": "3.5.14"
  "motion-v": "1.6.1"
  "vue-i18n": "10.0.8"
  "@fontsource-variable/inter": "5.2.5"
  "@vueuse/core": "13.2.0"
  "@vueuse/router": "13.2.0"
  "@wisemen/eslint-config-vue": "1.7.0"
  "eslint": "9.31.0"
  "husky": "^9.1.7"
  "reka-ui": "2.2.0"
  "tailwindcss": "4.1.7"
  "typescript": "5.8.3"
  "vite": "6.3.6"
  "vite-plugin-dts": "4.5.3"
  "vitest": "3.1.1"
  "vue-router": "4.5.1"
  "vue-tsc": "2.2.10"
  "tailwind-variants": "3.1.0"
  "tailwind-merge": "3.1.0"
  "@vitejs/plugin-vue": "5.2.4"
  "@tailwindcss/vite": "4.1.2"
  "@types/node": "22.15.21"
  "@vue/test-utils": "2.4.6"
  "@vue/tsconfig": "0.7.0"
  "turbo": "2.5.3"
  "rimraf": "6.0.1"
  "@tanstack/vue-query": "5.76.0"
  "unbuild": "3.5.0"
  "jsdom": "26.1.0"
  "bumpp": "10.1.1"
  "ts-node": "10.9.2"
  "esno": "4.8.0"
  "zod": "3.25.20"
