packages:
  - docs
  - "packages/*"

catalog:
  "tsdown": "0.15.4"
  "vue": "3.5.21"
  "motion-v": "1.7.1"
  "vue-i18n": "10.0.8"
  "@fontsource-variable/inter": "5.2.8"
  "@vueuse/core": "13.9.0"
  "@vueuse/router": "13.9.0"
  "@wisemen/eslint-config-vue": "1.7.3"
  "eslint": "9.36.0"
  "husky": "^9.1.7"
  "reka-ui": "2.5.0"
  "tailwindcss": "4.1.13"
  "typescript": "5.9.2"
  "vite": "6.3.6"
  "vite-plugin-dts": "4.5.4"
  "vitest": "3.2.4"
  "vue-router": "4.5.1"
  "vue-tsc": "3.0.8"
  "tailwind-variants": "3.1.1"
  "tailwind-merge": "3.3.1"
  "@vitejs/plugin-vue": "6.0.1"
  "@tailwindcss/vite": "4.1.13"
  "@types/node": "24.5.2"
  "@vue/test-utils": "2.4.6"
  "@vue/tsconfig": "0.8.1"
  "turbo": "2.5.8"
  "rimraf": "6.0.1"
  "@tanstack/vue-query": "5.90.2"
  "unbuild": "3.6.1"
  "jsdom": "27.0.0"
  "bumpp": "10.1.1"
  "ts-node": "10.9.2"
  "esno": "4.8.0"
  "zod": "4.1.11"
