packages:
  - docs
  - "packages/*"

catalogs:
  vue:
    "vue": "3.5.21"
    "motion-v": "1.7.1"
    "vue-i18n": "11.1.12"
    "@vueuse/core": "13.9.0"
    "@vueuse/router": "13.9.0"
    "reka-ui": "2.5.0"
    "vue-tsc": "3.0.8"
    "vue-router": "4.5.1"
    "@vue/tsconfig": "0.8.1"
    "@tanstack/vue-query": "5.90.2"
    "vue-sonner": "1.3.0"
  lint: 
    "eslint": "9.36.0"
    "@wisemen/eslint-config-vue": "1.7.3"
    "@antfu/eslint-config": "5.0.0"
    "@eslint/eslintrc": "3.3.1"
    "@intlify/eslint-plugin-vue-i18n": "4.0.1"
    "@typescript-eslint/parser": "8.38.0"
    "@vitest/eslint-plugin": "1.3.4"
    "@wisemen/eslint-plugin-vue": "0.0.1"
    "eslint-flat-config-utils": "2.1.0"
    "eslint-plugin-better-tailwindcss": "3.7.2"
    "eslint-plugin-check-file": "3.3.0"
    "eslint-plugin-format": "1.0.1"
    "eslint-plugin-import-newlines": "1.4.0"
    "eslint-plugin-newline-destructuring": "1.2.2"
    "eslint-plugin-path": "2.0.3"
    "eslint-plugin-perfectionist": "4.15.0"
    "eslint-plugin-project-structure": "3.13.3"
    "eslint-plugin-require-explicit-generics": "1.0.0"
    "eslint-plugin-simple-import-sort": "12.1.1"
    "eslint-plugin-unused-imports": "4.1.4"
    "eslint-plugin-vuejs-accessibility": "2.4.1"
    "eslint-typegen": "2.3.0"
    "globals": "16.3.0"
    "@typescript-eslint/scope-manager": "8.35.0"
    "@typescript-eslint/type-utils": "8.35.0"
    "@typescript-eslint/utils": "8.35.0"
  build: 
    "tsdown": "0.15.4"
    "husky": "^9.1.7"
    "typescript": "5.9.2"
    "turbo": "2.5.8"
    "rimraf": "6.0.1"
    "bumpp": "10.1.1"
    "chalk": "5.4.1"
    "commander": "13.1.0"
    "tsx": "4.16.0"
  vite: 
    "vite": "7.1.7"
    "vite-plugin-dts": "4.5.4"
    "@vitejs/plugin-vue": "6.0.1"
    "@tailwindcss/vite": "4.1.13"
  test:
    "vitest": "3.2.4"
    "@vue/test-utils": "2.4.6"
    "jsdom": "27.0.0"
  style: 
    "tailwindcss": "4.1.13"
    "tailwind-variants": "3.1.1"
    "tailwind-merge": "3.3.1"
    "sass": "1.77.5"
    "postcss": "8.4.38"
    "postcss-prefix-selector": "1.16.1"
    "@tailwindcss/postcss": "4.0.0-beta.8"
  types: 
    "@types/node": "24.5.2"
    "@types/ejs": "3.1.5"
    "@types/fs-extra": "11.0.4"
    "@types/google.maps": "3.58.1"
    "@types/babel__traverse": "7.20.6"
    "@types/markdown-it": "14.1.1"
    "@tsconfig/node18": "18.2.4"
  general:
    "zod": "4.1.11"
    "neverthrow": "8.2.0"
    "graphemer": "1.4.0"
    "ts-api-utils": "2.1.0"
    "pkce-challenge": "4.1.0"
    "@googlemaps/js-api-loader": "1.16.8"
    "blurhash": "2.0.5"
    "libphonenumber-js": "1.11.3"
    "highlight-words": "2.0.0"
  stories:
    "histoire": "1.0.0-alpha.2"
    "@histoire/plugin-vue": "1.0.0-alpha.2"
  docs:
    "vitepress": "1.6.3"
    "vue-component-meta": "2.0.24"
    "markdown-it": "14.1.0"
  date:
    "@internationalized/date": "3.5.4"
  openapi:
    "@hey-api/openapi-ts": "0.81.0"
  tooling:
    "@commitlint/cli": "19.8.1"
    "@commitlint/config-conventional": "19.8.1"
    "@changesets/cli": "2.29.5"
  telemetry:
    "@opentelemetry/context-zone": "2.0.1"
    "@opentelemetry/core": "2.0.1"
    "@opentelemetry/exporter-trace-otlp-http": "0.203.0"
    "@opentelemetry/instrumentation": "0.203.0"
    "@opentelemetry/instrumentation-fetch": "0.203.0"
    "@opentelemetry/instrumentation-user-interaction": "0.48.0"
    "@opentelemetry/otlp-exporter-base": "0.203.0"
    "@opentelemetry/resources": "2.0.1"
    "@opentelemetry/sdk-trace-base": "2.0.1"
    "@opentelemetry/sdk-trace-web": "2.0.1"
    "@sentry/vue": "10.0.0"


