import { tv } from '@/libs/twVariants.lib'

export const selectItemStyle = tv({
  slots: {
    item: 'group flex cursor-default items-center justify-between rounded-select-item-border-radius-default bg-select-item-bg-color-default px-select-item-padding-x-default py-select-item-padding-y-default text-select-item-font-size-default font-select-item-font-weight-default text-select-item-text-color-default outline-none duration-200 hover:bg-select-item-bg-color-hover hover:text-select-item-text-color-hover data-[disabled]:cursor-not-allowed data-[disabled]:bg-select-item-bg-color-disabled data-[highlighted]:bg-select-item-bg-color-highlighted data-[state=checked]:bg-select-item-bg-color-selected data-[state=checked]:data-[highlighted]:bg-select-item-bg-color-highlighted data-[disabled]:text-select-item-text-color-disabled data-[state=checked]:text-select-item-text-color-selected data-[disabled]:hover:bg-select-item-bg-color-disabled data-[highlighted]:hover:bg-select-item-bg-color-hover data-[state=checked]:hover:bg-select-item-bg-color-hover hover:data-[disabled]:bg-select-item-bg-color-disabled',
    multipleValueIndicator: 'flex h-select-item-multiple-value-indicator-size-default w-select-item-multiple-value-indicator-size-default items-center justify-center rounded-select-item-multiple-value-indicator-border-radius-default border border-solid border-transparent duration-100 [--icon-color:var(--select-item-multiple-value-indicator-color-selected)] group-hover:border-select-item-multiple-value-indicator-border-color-hover group-data-[highlighted]:border-select-item-multiple-value-indicator-border-color-hover group-data-[state=checked]:border-select-item-multiple-value-indicator-border-color-selected group-data-[state=checked]:bg-select-item-multiple-value-indicator-bg-color-selected group-hover:group-data-[disabled]:border-transparent',
    singleValueIndicator: 'h-select-item-single-value-indicator-size-default w-select-item-single-value-indicator-size-default text-select-item-single-value-indicator-color-default',
  },
})
