export { useDialog as useDialogNext } from './dialog.composable'
export type { DialogProps as VcDialogNextProps } from './dialog.props'
export { default as VcDialogNext } from './Dialog.vue'
export { default as VcDialogNextContainer } from './DialogContainer.vue'
export { default as VcDialogNextCloseButton } from './parts/DialogCloseButton.vue'
export { default as VcDialogNextContent } from './parts/DialogContent.vue'
export { default as VcDialogNextContentTransition } from './parts/DialogContentTransition.vue'
export { default as VcDialogNextDescription } from './parts/DialogDescription.vue'
export { default as VcDialogNextOverlay } from './parts/DialogOverlay.vue'
export { default as VcDialogNextOverlayTransition } from './parts/DialogOverlayTransition.vue'
export { default as VcDialogNextPortal } from './parts/DialogPortal.vue'
export { default as VcDialogNextRoot } from './parts/DialogRoot.vue'
export { default as VcDialogNextTitle } from './parts/DialogTitle.vue'
