import '@/styles/index.scss'
import '@/components/button/button/buttonStyle.config'
import '@/components/button/icon-button/iconButtonStyle.config'
import '@/components/checkbox/checkboxStyle.config'
import '@/components/dropdown-menu/dropdownMenuStyle.config'
import '@/components/icon/iconStyle.config'
import '@/components/input-field-error/inputFieldErrorStyle.config'
import '@/components/input-field-hint/inputFieldHintStyle.config'
import '@/components/input-field-label/inputFieldLabelStyle.config'
import '@/components/input-field/text-field/textFieldStyle.config'
import '@/components/popover/popoverStyle.config'
import '@/components/select/selectStyle.config'
import '@/components/switch/switchStyle.config'
import '@/components/table/tableStyle.config'
import '@/components/tabs/tabsStyle.config'
import '@/components/tag/tagStyle.config'
import '@/components/tooltip/tooltipStyle.config'

export * from '@/components'
export * from '@/composables'
export * from '@/types'

// Icons
export type { Icon, Icons } from '@/icons/icons'
export { extendIcons } from '@/icons/icons'
