export { default as VcTableCell } from '@/components/table/parts/TableCell.vue'
export { default as VcTableHeadercell } from '@/components/table/parts/TableHeaderCell.vue'
export { default as VcTableInteractiveElement } from '@/components/table/parts/TableInteractiveElement.vue'
export { default as VcTableRow } from '@/components/table/parts/TableRow.vue'
export type { TableProps as VcTableProps } from '@/components/table/table.props'
export type { TableColumn } from '@/components/table/table.type'
export { default as VcTable } from '@/components/table/Table.vue'
