import { defineStyleConfig } from '@/styling/defineStyleConfig'

export interface TextFieldStyleConfig {
  '--text-field-bg-color-default': string
  '--text-field-bg-color-disabled': string
  '--text-field-bg-color-error': string
  '--text-field-bg-color-focus': string
  '--text-field-bg-color-hover': string
  '--text-field-border-bottom-color-default': string
  '--text-field-border-bottom-color-disabled': string
  '--text-field-border-bottom-color-error': string
  '--text-field-border-bottom-color-focus': string
  '--text-field-border-bottom-color-hover': string
  '--text-field-border-left-color-default': string
  '--text-field-border-left-color-disabled': string
  '--text-field-border-left-color-error': string
  '--text-field-border-left-color-focus': string
  '--text-field-border-left-color-hover': string
  '--text-field-border-radius-bottom-left-default': string
  '--text-field-border-radius-bottom-right-default': string
  '--text-field-border-radius-top-left-default': string
  '--text-field-border-radius-top-right-default': string
  '--text-field-border-right-color-default': string
  '--text-field-border-right-color-disabled': string
  '--text-field-border-right-color-error': string
  '--text-field-border-right-color-focus': string
  '--text-field-border-right-color-hover': string
  '--text-field-border-top-color-default': string
  '--text-field-border-top-color-disabled': string
  '--text-field-border-top-color-error': string
  '--text-field-border-top-color-focus': string
  '--text-field-border-top-color-hover': string
  '--text-field-font-size-default': string
  '--text-field-font-weight-default': string
  '--text-field-height-default': string
  '--text-field-icon-color-default': string
  '--text-field-icon-color-disabled': string
  '--text-field-icon-color-error': string
  '--text-field-icon-color-focus': string
  '--text-field-icon-color-hover': string
  '--text-field-icon-left-spacing-default': string
  '--text-field-icon-right-spacing-default': string
  '--text-field-icon-size-default': string
  '--text-field-loader-color-default': string
  '--text-field-loader-color-disabled': string
  '--text-field-loader-color-error': string
  '--text-field-loader-color-focus': string
  '--text-field-loader-color-hover': string
  '--text-field-loader-size-default': string
  '--text-field-padding-left-default': string
  '--text-field-padding-right-default': string
  '--text-field-placeholder-color-default': string
  '--text-field-placeholder-color-disabled': string
  '--text-field-placeholder-color-error': string
  '--text-field-placeholder-color-focus': string
  '--text-field-placeholder-color-hover': string
  '--text-field-ring-color-error': string
  '--text-field-ring-color-focus': string
  '--text-field-shadow-default': string
  '--text-field-shadow-disabled': string
  '--text-field-shadow-error': string
  '--text-field-shadow-focus': string
  '--text-field-shadow-hover': string
  '--text-field-text-color-default': string
  '--text-field-text-color-disabled': string
  '--text-field-text-color-error': string
  '--text-field-text-color-focus': string
  '--text-field-text-color-hover': string
  '--text-field-with-icon-left-padding-left-default': string
  '--text-field-with-icon-right-padding-right-default': string
}

export function setupDefaultTextFieldStyles(): void {
// Default
  defineStyleConfig({
    colorScheme: '*',
    config: {
      '--text-field-bg-color-default': 'var(--bg-primary)',
      '--text-field-bg-color-disabled': 'var(--bg-disabled-subtle)',
      '--text-field-bg-color-error': 'var(--bg-primary)',
      '--text-field-bg-color-focus': 'var(--bg-primary)',
      '--text-field-bg-color-hover': 'var(--bg-primary)',
      '--text-field-border-bottom-color-default': 'var(--border-primary)',
      '--text-field-border-bottom-color-disabled': 'var(--border-disabled)',
      '--text-field-border-bottom-color-error': 'var(--border-error-subtle)',
      '--text-field-border-bottom-color-focus': 'var(--border-brand)',
      '--text-field-border-bottom-color-hover': 'var(--border-primary)',
      '--text-field-border-left-color-default': 'var(--border-primary)',
      '--text-field-border-left-color-disabled': 'var(--border-disabled)',
      '--text-field-border-left-color-error': 'var(--border-error-subtle)',
      '--text-field-border-left-color-focus': 'var(--border-brand)',
      '--text-field-border-left-color-hover': 'var(--border-primary)',
      '--text-field-border-radius-bottom-left-default': 'var(--radius-md)',
      '--text-field-border-radius-bottom-right-default': 'var(--radius-md)',
      '--text-field-border-radius-top-left-default': 'var(--radius-md)',
      '--text-field-border-radius-top-right-default': 'var(--radius-md)',
      '--text-field-border-right-color-default': 'var(--border-primary)',
      '--text-field-border-right-color-disabled': 'var(--border-disabled)',
      '--text-field-border-right-color-error': 'var(--border-error-subtle)',
      '--text-field-border-right-color-focus': 'var(--border-brand)',
      '--text-field-border-right-color-hover': 'var(--border-primary)',
      '--text-field-border-top-color-default': 'var(--border-primary)',
      '--text-field-border-top-color-disabled': 'var(--border-disabled)',
      '--text-field-border-top-color-error': 'var(--border-error-subtle)',
      '--text-field-border-top-color-focus': 'var(--border-brand)',
      '--text-field-border-top-color-hover': 'var(--border-primary)',
      '--text-field-font-size-default': 'var(--text-sm)',
      '--text-field-font-weight-default': '400',
      '--text-field-height-default': '2.5rem',
      '--text-field-icon-color-default': 'var(--fg-quaternary)',
      '--text-field-icon-color-disabled': 'var(--fg-quaternary)',
      '--text-field-icon-color-error': 'var(--fg-error-secondary)',
      '--text-field-icon-color-focus': 'var(--fg-quaternary)',
      '--text-field-icon-color-hover': 'var(--fg-quaternary)',
      '--text-field-icon-left-spacing-default': 'var(--spacing-lg)',
      '--text-field-icon-right-spacing-default': 'var(--spacing-lg)',
      '--text-field-icon-size-default': '1.125rem',
      '--text-field-loader-color-default': 'var(--fg-quaternary)',
      '--text-field-loader-color-disabled': 'var(--fg-quaternary)',
      '--text-field-loader-color-error': 'var(--fg-error-secondary)',
      '--text-field-loader-color-focus': 'var(--fg-quaternary)',
      '--text-field-loader-color-hover': 'var(--fg-quaternary)',
      '--text-field-loader-size-default': '0.875rem',
      '--text-field-padding-left-default': 'var(--spacing-lg)',
      '--text-field-padding-right-default': 'var(--spacing-lg)',
      '--text-field-placeholder-color-default': 'var(--text-placeholder)',
      '--text-field-placeholder-color-disabled': 'var(--text-placeholder)',
      '--text-field-placeholder-color-error': 'var(--text-placeholder)',
      '--text-field-placeholder-color-focus': 'var(--text-placeholder)',
      '--text-field-placeholder-color-hover': 'var(--text-placeholder)',
      '--text-field-ring-color-error': 'var(--error-500)',
      '--text-field-ring-color-focus': 'var(--brand-500)',
      '--text-field-shadow-default': 'var(--shadow-xs)',
      '--text-field-shadow-disabled': 'var(--shadow-xs)',
      '--text-field-shadow-error': 'var(--shadow-xs)',
      '--text-field-shadow-focus': 'var(--shadow-xs)',
      '--text-field-shadow-hover': 'var(--shadow-xs)',
      '--text-field-text-color-default': 'var(--text-primary)',
      '--text-field-text-color-disabled': 'var(--text-disabled)',
      '--text-field-text-color-error': 'var(--text-primary)',
      '--text-field-text-color-focus': 'var(--text-primary)',
      '--text-field-text-color-hover': 'var(--text-primary)',
      '--text-field-with-icon-left-padding-left-default': 'var(--spacing-md)',
      '--text-field-with-icon-right-padding-right-default': 'var(--spacing-md)',
    },
    theme: '*',
    variant: 'default',
    component: 'textField',
  })
}
