import type { Config } from 'tailwindcss'

export const textFieldTailwindConfig = {
  backgroundColor: {
    'text-field-bg-color-default': 'var(--text-field-bg-color-default)',
    'text-field-bg-color-disabled': 'var(--text-field-bg-color-disabled)',
    'text-field-bg-color-error': 'var(--text-field-bg-color-error)',
    'text-field-bg-color-focus': 'var(--text-field-bg-color-focus)',
    'text-field-bg-color-hover': 'var(--text-field-bg-color-hover)',
  },
  borderColor: {
    'text-field-border-bottom-color-default': 'var(--text-field-border-bottom-color-default)',
    'text-field-border-bottom-color-disabled': 'var(--text-field-border-bottom-color-disabled)',
    'text-field-border-bottom-color-error': 'var(--text-field-border-bottom-color-error)',
    'text-field-border-bottom-color-focus': 'var(--text-field-border-bottom-color-focus)',

    'text-field-border-bottom-color-hover': 'var(--text-field-border-bottom-color-hover)',
    'text-field-border-left-color-default': 'var(--text-field-border-left-color-default)',
    'text-field-border-left-color-disabled': 'var(--text-field-border-left-color-disabled)',
    'text-field-border-left-color-error': 'var(--text-field-border-left-color-error)',

    'text-field-border-left-color-focus': 'var(--text-field-border-left-color-focus)',
    'text-field-border-left-color-hover': 'var(--text-field-border-left-color-hover)',
    'text-field-border-right-color-default': 'var(--text-field-border-right-color-default)',
    'text-field-border-right-color-disabled': 'var(--text-field-border-right-color-disabled)',

    'text-field-border-right-color-error': 'var(--text-field-border-right-color-error)',
    'text-field-border-right-color-focus': 'var(--text-field-border-right-color-focus)',
    'text-field-border-right-color-hover': 'var(--text-field-border-right-color-hover)',
    'text-field-border-top-color-default': 'var(--text-field-border-top-color-default)',

    'text-field-border-top-color-disabled': 'var(--text-field-border-top-color-disabled)',
    'text-field-border-top-color-error': 'var(--text-field-border-top-color-error)',
    'text-field-border-top-color-focus': 'var(--text-field-border-top-color-focus)',
    'text-field-border-top-color-hover': 'var(--text-field-border-top-color-hover)',
  },
  borderRadius: {
    'text-field-border-radius-bottom-left-default': 'var(--text-field-border-radius-bottom-left-default)',
    'text-field-border-radius-bottom-right-default': 'var(--text-field-border-radius-bottom-right-default)',
    'text-field-border-radius-top-left-default': 'var(--text-field-border-radius-top-left-default)',
    'text-field-border-radius-top-right-default': 'var(--text-field-border-radius-top-right-default)',
  },
  boxShadow: {
    'text-field-shadow-default': 'var(--text-field-shadow-default)',
    'text-field-shadow-disabled': 'var(--text-field-shadow-disabled)',
    'text-field-shadow-error': 'var(--text-field-shadow-error)',
    'text-field-shadow-focus': 'var(--text-field-shadow-focus)',
    'text-field-shadow-hover': 'var(--text-field-shadow-hover)',
  },
  fontSize: {
    'text-field-error-font-size-default': 'var(--text-field-error-font-size-default)',
    'text-field-font-size-default': 'var(--text-field-font-size-default)',
    'text-field-hint-font-size-default': 'var(--text-field-hint-font-size-default)',
    'text-field-label-font-size-default': 'var(--text-field-label-font-size-default)',
  },
  fontWeight: {
    'text-field-error-font-weight-default': 'var(--text-field-error-font-weight-default)',
    'text-field-font-weight-default': 'var(--text-field-font-weight-default)',
    'text-field-hint-font-weight-default': 'var(--text-field-hint-font-weight-default)',
    'text-field-label-font-weight-default': 'var(--text-field-label-font-weight-default)',
  },
  height: {
    'text-field-height-default': 'var(--text-field-height-default)',
    'text-field-icon-size-default': 'var(--text-field-icon-size-default)',
    'text-field-loader-size-default': 'var(--text-field-loader-size-default)',
  },
  margin: {
    'text-field-error-spacing-default': 'var(--text-field-error-spacing-default)',
    'text-field-hint-spacing-default': 'var(--text-field-hint-spacing-default)',
    'text-field-icon-left-spacing-default': 'var(--text-field-icon-left-spacing-default)',
    'text-field-icon-right-spacing-default': 'var(--text-field-icon-right-spacing-default)',
    'text-field-label-spacing-default': 'var(--text-field-label-spacing-default)',
    'text-field-padding-left-default': 'var(--text-field-padding-left-default)',
    'text-field-padding-right-default': 'var(--text-field-padding-right-default)',
  },
  padding: {
    'text-field-padding-left-default': 'var(--text-field-padding-left-default)',
    'text-field-padding-right-default': 'var(--text-field-padding-right-default)',
    'text-field-with-icon-left-padding-left-default': 'var(--text-field-with-icon-left-padding-left-default)',
    'text-field-with-icon-right-padding-right-default': 'var(--text-field-with-icon-right-padding-right-default)',
  },
  ringColor: {
    'text-field-ring-color-error': 'var(--text-field-ring-color-error)',
    'text-field-ring-color-focus': 'var(--text-field-ring-color-focus)',
  },
  textColor: {
    'text-field-error-text-color-default': 'var(--text-field-error-text-color-default)',
    'text-field-hint-text-color-default': 'var(--text-field-hint-text-color-default)',
    'text-field-hint-text-color-disabled': 'var(--text-field-hint-text-color-disabled)',
    'text-field-hint-text-color-error': 'var(--text-field-hint-text-color-error)',
    'text-field-hint-text-color-focus': 'var(--text-field-hint-text-color-focus)',
    'text-field-hint-text-color-hover': 'var(--text-field-hint-text-color-hover)',
    'text-field-label-text-color-default': 'var(--text-field-label-text-color-default)',
    'text-field-label-text-color-disabled': 'var(--text-field-label-text-color-disabled)',
    'text-field-label-text-color-error': 'var(--text-field-label-text-color-error)',
    'text-field-label-text-color-focus': 'var(--text-field-label-text-color-focus)',
    'text-field-label-text-color-hover': 'var(--text-field-label-text-color-hover)',
    'text-field-loader-color-default': 'var(--text-field-loader-color-default)',
    'text-field-loader-color-disabled': 'var(--text-field-loader-color-disabled)',
    'text-field-loader-color-error': 'var(--text-field-loader-color-error)',
    'text-field-loader-color-focus': 'var(--text-field-loader-color-focus)',
    'text-field-loader-color-hover': 'var(--text-field-loader-color-hover)',
    'text-field-placeholder-color-default': 'var(--text-field-placeholder-color-default)',
    'text-field-placeholder-color-disabled': 'var(--text-field-placeholder-color-disabled)',
    'text-field-placeholder-color-error': 'var(--text-field-placeholder-color-error)',
    'text-field-placeholder-color-focus': 'var(--text-field-placeholder-color-focus)',
    'text-field-placeholder-color-hover': 'var(--text-field-placeholder-color-hover)',
    'text-field-text-color-default': 'var(--text-field-text-color-default)',
    'text-field-text-color-disabled': 'var(--text-field-text-color-disabled)',
    'text-field-text-color-error': 'var(--text-field-text-color-error)',
    'text-field-text-color-focus': 'var(--text-field-text-color-focus)',
    'text-field-text-color-hover': 'var(--text-field-text-color-hover)',
  },
  width: {
    'text-field-loader-size-default': 'var(--text-field-loader-size-default)',
  },
} satisfies Config['theme']
