export type { BadgeProps as VcBadgeProps } from '@/components/badge/badge.props'
export { default as VcBadge } from '@/components/badge/Badge.vue'
export { default as VcBadgeIcon } from '@/components/badge/parts/BadgeIcon.vue'
export { default as VcBadgeRemoveButton } from '@/components/badge/parts/BadgeRemoveButton.vue'
export { default as VcBadgeRoot } from '@/components/badge/parts/BadgeRoot.vue'
