---
name: Publish Docs

on:
  push:
    branches: ['main', 'v2']
  workflow_dispatch:

jobs:
  publish-docs:
    uses: wisemen-digital/devops-github-actions/.github/workflows/node-publish-docs.yml@main
    with:
      dist-path: docs/.vitepress/dist/
