---
name: Publish Docs

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - main
    workflow_dispatch:

jobs:
  publish-docs:
    uses: wisemen-digital/devops-github-actions/.github/workflows/node-publish-docs.yml@main
